In [14]:
import numpy as np
import tensorflow as tf
from matplotlib import pyplot as plt
import math
import random


def SoftMax(values):
    answers = [0]*len(values)
    denom = 0
    for i in range(len(values)):
        denom += math.exp(values[i])
    for i in range(len(values)):
        answers[i] = math.exp(values[i])/denom
    return answers


def OneHot(label):
    ans = [0]*10
    ans[label] = 1
    return ans


class neuralnet:

    def __init__(self, numinputs, numoutputs, errorfunc="MSE"):

        self.numinputs = numinputs
        self.numoutputs = numoutputs
        self.errorfunc = errorfunc
        
        self.biases = np.random.default_rng().random(self.numoutputs)
        self.weights = np.random.default_rng().random((self.numoutputs, self.numinputs))

    def evaluate(self, inputs):
            try:
                output = self.weights @ inputs + self.biases
                return output
            except:
                print("Dimension mismatch!")

    def computeerror(self, outputs, trueoutputs):
         if self.errorfunc == "MSE":
            pass # You need to put the MSE stuff here
         

         if self.errorfunc == "CrossEntropy":
            sum = 0
            for i in range(0, len(outputs)):
                sum += -trueoutputs[i]*math.log2(outputs[i])
            return sum


    def computegradient(self, inputs, labels):

        wparts = np.zeros((self.numoutputs, self.numinputs))
        bparts = np.zeros(self.numoutputs)

        if self.errorfunc == "MSE":
            
            # You need to put stuff here


            return (wparts, bparts)


        if self.errorfunc == "CrossEntropy":

            # FIX THIS SECTION

            ys = self.weights @ inputs + self.biases
            softdenom = 0

            for i in range(len(ys)):
                softdenom += math.exp(ys[i])

            zs = SoftMax(ys)
            
            M3 = np.zeros((self.numoutputs, self.numoutputs, self.numinputs))
            for i in range(self.numoutputs):
                for j in range(self.numinputs):
                    M3[i,i,j] = inputs[j]

            M2 = np.zeros((self.numoutputs, self.numoutputs))
            for i in range(self.numoutputs):
                for j in range(self.numoutputs):
                    if (i == j):
                        M2[i,j] = ((softdenom)*math.exp(ys[j]) - math.exp(2*ys[j])) / (softdenom**2)
                    else:
                        M2[i,j] = -(math.exp(ys[i]+ys[j])) / (softdenom ** 2)

            M1 = np.zeros((self.numoutputs))
            for i in range(self.numoutputs):
                M1[i] = -labels[i] / (zs[i] * math.log(2))
        

            wparts = M1 @ (M2 @ M3)
            bparts = M1 @ M2
            
            print(M1)

            return (wparts, bparts)

       

        
    
    def updateweights(self, wparts, bparts, eta):

        # This doesn't need to be changed, since all it takes in are
        # the partial derivatives computed elsewhere

        self.weights -= eta*wparts
        self.biases -= eta*bparts



In [15]:
#Instantiate network and set weights/biases
NNAssignment4 = neuralnet(2,2,"CrossEntropy")
NNAssignment4.weights = np.array([[0.1, 0.2], [0.3, 0.4]])
NNAssignment4.biases = np.array([0.7, 0.8])


print(NNAssignment4.weights)
print(NNAssignment4.biases)

NNAssignment4.weights @ np.array([0.5, 0.6]) + NNAssignment4.biases


[[0.1 0.2]
 [0.3 0.4]]
[0.7 0.8]


array([0.87, 1.19])

In [16]:
(wparts, bparts) = NNAssignment4.computegradient([0.5,0.6],[1,0])

print(wparts)
print(bparts)

[-3.42947044  0.        ]
[[-0.41789411 -0.50147294]
 [ 0.41789411  0.50147294]]
[-0.83578823  0.83578823]
